### ISSUE TITLE
Issue when trying access to macrodata

### ISSUE THREAD

**Issue by strayMat** [InseeFrLab/pynsee#40]
Salut ! Thx for the great work !

I am trying to get data from the BDM API without success. I registered to the macro API and got access keys but can't access any serie.  The other API seem to work well (sirene, localdata or metadata). 

Steps to reproduce:

```python
con = init_conn(insee_key=INSEE_API_KEY, insee_secret=INSEE_API_SECRET)
from pynsee.macrodata import *

idbank_ipc = get_series_list("IPC-2015", "CLIMAT-AFFAIRES")
```

Yield following error :
```
!!! An error occurred !!!
Query : https://api.insee.fr/series/BDM/V1/dataflow/FR1/all

!!! SDMX web service used instead of API !!!
````

**Comment by hadrilec** [comment]
Hi @strayMat, thank you for your feedback!
I get same error from your code. Either it is the underlying functions or it is because INSEE's APIs are under maintenance these days [link](https://api.insee.fr/catalogue/site/themes/wso2/subthemes/insee/pages/item-info.jag?name=BDM&version=V1&provider=insee).
I will double check in the coming days to make sure it is not related to any package flaw.
Best regards,
Hadrien

**Comment by strayMat** [comment]
Thanks ! I'll double check too in the coming days !

**Comment by hadrilec** [comment]
It seems that BDM API is now back on track ;)
At least the following code is now working on my side:
`from pynsee.macrodata import *
idbank_ipc = get_series_list("IPC-2015", "CLIMAT-AFFAIRES")`
Best,
