### ISSUE TITLE
Extending geopandas methods and attributes to geodata objects

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/pynsee#78]
@hadrilec 
I started to use `geodata` package for my `Python` class, thanks a lot it is very convenient. 

I have remarked a few things:

## Object class

```python
communes = get_geodata('ADMINEXPRESS-COG-CARTO.LATEST:commune')
```

`communes ` is of class `pynsee.geodata.GeoDataframe.GeoDataframe`: 

- The repeated `GeoDataframe` is a typo ?
- Maybe would be better to use the same convention than `geopandas` thus `GeoDataFrame`

## CRS

CRS of `communes ` is not set. I think we could handle that internally when setting the class (in order to inherit the attribute of gpd.GeoDataFrame` object)

## Extension of geopandas methods

The following code will fail if the object is not coerced to a `gpd` object (while it will work with a gpd object). 
There's something to be done for our class to inherit gpd methods

```python
paris = communes.loc[communes['insee'].str.startswith("75")]

fig,ax = plt.subplots(figsize=(10, 10))
paris.plot(ax = ax, alpha=0.5, edgecolor='blue')
ctx.add_basemap(ax, crs = paris.crs.to_string())
ax.set_axis_off()
ax
```

**Comment by hadrilec** [comment]
Indeed, the class name can be confusing for the users.

I think the main objective of the package is to disseminate data not to provide tools to make plots. So I would suggest not to make available a new method, but to show the users that the data can be easily converted to a geopandas.geodataframe.

For maintainance purposes, I woul prefer not to depend on geopandas, as the underlying gdal library is sometimes not easy to install on work computers.

A solution could be to change GeoDataframe class name to something else because it seems to be misleading for users, I will try to come up with a new class name. I create a new issue specifically focusing on this topic #82

**Comment by hadrilec** [comment]
as a replacement, we chose GeoFrDataFrame. It should be clearer now that this class should not be understood as working as geopandas.GeoDataFrame : https://pynsee.readthedocs.io/en/latest/get_data.html#pynsee.geodata.GeoFrDataFrame.GeoFrDataFrame
